### ISSUE TITLE
GUI recordings taken with GUI v0.6.1 cannot be read with `open ephys python tools`

### ISSUE THREAD

**Issue by lillysanchez** [open-ephys/open-ephys-python-tools#15]
I made a recording with OpenEphys GUI v0.6.1, but I can't read the recording with the current master of the `open ephys python tools`. The issue is that there is no *continuous* or *event* data being read. This is despite the presence of this data in the folder structure. 

The error trace is:
```console
Traceback (most recent call last):
  File "/Users/lillyothevalley/lfp-code/load_oephys_data.py", line 44, in <module>
    lfp = session.recordnodes[0].recordings[0].continuous[0].samples
  File "/opt/anaconda3/lib/python3.8/site-packages/open_ephys/analysis/recording.py", line 64, in continuous
    self.load_continuous()
  File "/opt/anaconda3/lib/python3.8/site-packages/open_ephys/analysis/formats/BinaryRecording.py", line 85, in load_continuous
    c = self.Continuous(info, self.directory)
  File "/opt/anaconda3/lib/python3.8/site-packages/open_ephys/analysis/formats/BinaryRecording.py", line 59, in __init__
    self.metadata['subprocessor_id'] = info['source_processor_sub_idx']
KeyError: 'source_processor_sub_idx'
```

**Comment by jsiegle** [comment]
Hi Lilly,

We have a separate branch of code for v0.6.x: https://github.com/open-ephys/open-ephys-python-tools/tree/0.6.0

Soon we will make this the default branch, and make it installable via `pip`.

**Comment by lillysanchez** [comment]
I'm attempting to use Branch 0.6.0, but it is no longer available on GitHub. I am using open-ephys GUI 0.6.1 but the tool can't read it. The error is the same as above.

**Comment by jsiegle** [comment]
Hi Lilly – the `main` branch is now compatible with data saved by all 0.6.x versions, and is also available on PyPI. If you create a new Python environment and run `pip install open-ephys-python-tools`, are you able to read the data? If not, what is the error message?
